# Run unit tests using CTest
name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@v2

      - name: Set up dependencies
        run: sudo apt-get install -y cmake build-essential

      - name: Create build directory
        run: mkdir build

      - name: Run CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run CTest
        run: ctest --output-on-failure --test-dir build